"""initial migration

Revision ID: 7e56e059ae05
Revises: 
Create Date: 2024-08-28 15:57:24.545806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e56e059ae05'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'description', name='uq_language_description')
    )
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_language_language'), ['language'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_language'))
        batch_op.drop_index(batch_op.f('ix_language_description'))

    op.drop_table('language')
    # ### end Alembic commands ###
