"""Rebuild

Revision ID: a2e717a4016a
Revises: d419a6421c40
Create Date: 2024-09-05 10:38:04.980908

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2e717a4016a'
down_revision = 'd419a6421c40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('language', 'description', name='uq_language_description')
    )
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_language_description'), ['description'], unique=False)
        batch_op.create_index(batch_op.f('ix_language_language'), ['language'], unique=True)

    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('definition', sa.String(length=128), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'definition', name='uq_word_definition')
    )
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_word'), ['word'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_word'))
        batch_op.drop_index(batch_op.f('ix_word_definition'))

    op.drop_table('word')
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_language_language'))
        batch_op.drop_index(batch_op.f('ix_language_description'))

    op.drop_table('language')
    # ### end Alembic commands ###
