"""Word model update 3

Revision ID: a69f81220025
Revises: b399b2972f86
Create Date: 2024-09-05 09:52:48.728426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a69f81220025'
down_revision = 'b399b2972f86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=128), nullable=False),
    sa.Column('definition', sa.String(length=128), nullable=True),
    sa.Column('language_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['language_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('word', 'definition', name='uq_word_definition')
    )
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_word_definition'), ['definition'], unique=False)
        batch_op.create_index(batch_op.f('ix_word_word'), ['word'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_word_word'))
        batch_op.drop_index(batch_op.f('ix_word_definition'))

    op.drop_table('word')
    # ### end Alembic commands ###
